### ISSUE TITLE
研究如何对代码进行调试

### ISSUE THREAD

**Issue by zhaoxu98** [ccagml/leetcode_ext#164]
目前没有发现有这项功能

**Comment by ccagml** [comment]
😂没有,你会弄吗?

**Comment by ccagml** [comment]
语言种类太多了,不清楚是不是写个main函数就能调用vscode的调试器

**Comment by zhaoxu98** [comment]
> 语言种类太多了,不清楚是不是写个main函数就能调用vscode的调试器

我去研究一下怎么调用，感谢回复。
